server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    # MySQL数据源配置
    mysql:
#      jdbc-url: jdbc:mysql://localhost:3306/zfine_java?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: root
      jdbc-url: jdbc:mysql://39.106.228.205:3306/zfine_java?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: ykxj2020@
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20 #连接池的最大数据库连接数。设为0表示无限制
      initialSize: 1  #初始化连接:连接池启动时创建的初始化连接数量
      maxWait: 60000   #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
      minIdle: 1  #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,低于这个数量将创建新的连接
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validation-query: "SELECT 'X' FROM DUAL"
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

    # clickhouse数据源配置
    clickhouse:
      jdbc-url: jdbc:clickhouse://localhost:8123/test
      username: default
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        validation-query: select 1
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
# 自定义redis key
redis:
  database: zfine
  key:
    user: 'user'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  token:
    #JWT存储的请求头
    tokenHeader: Authorization
    #  token过期时间，单位分钟
    tokenExpireTime: 120
    #  RefreshToken过期时间，单位：分钟, 24*60=1440
    refreshTokenExpireTime: 1440
    #  shiro缓存有效期，单位分钟,2*60=120
    shiroCacheExpireTime: 120
    #  token加密密钥
    secretKey: storywebkey

